Makefile
config/default/kustomization.yaml
config/manager/kustomization.yaml
config/manager/mysql.yaml
config/manager/namespace.yaml
config/manager/service.yaml

完善mysql在k8s环境部署的配置文件。
用户可以根据自己的需求，在k8s部署mysql服务。

doc:[pub] 完善mysql在k8s环境部署的配置文件

---

web/src/components/PromLayout/GithubButton/index.tsx
web/src/components/PromLayout/PromLayout.tsx
web/src/pages/login/index.tsx
web/src/pages/login/style/login.module.less

feat: 增加GitHub地址

---

app/prom_agent/internal/server/watch.go
app/prom_agent/internal/service/load.go
app/prom_server/internal/server/event.go
pkg/strategy/alert.go
pkg/util/interflow/hook_interflow.go

1. server event调整核心逻辑
2. agent watch调整交互逻辑
3. agent alert调整日志记录
4. hook interflow调整退出逻辑

fix(server和agent通信): 修复server和agent通信异常问题，增加重试和超时逻辑

---

pkg/strategy/alarm.go
pkg/strategy/alert.go

1. 解决agent alert时候label共用变量导致数据错误

feat(agent alert): 解决agent alert时候labels错误问题

---

.github/ISSUE_TEMPLATE/bug-report.yaml

/kind feat
add issue template file
Fixes #
```release-note
NONE
```

feat: add issue template file

---

app/prom_server/internal/data/repositiryimpl/strategy/strategy.go
web/src/components/PromLayout/PromLayout.tsx
web/src/components/PromLayout/SiderMenu/SiderMenu.tsx
web/src/pages/home/monitor/alarm-group/index.tsx
web/src/pages/home/monitor/chat-hook/index.tsx
web/src/pages/home/monitor/endpoint/index.tsx
web/src/pages/home/monitor/strategy-group/child/EditGroupModal.tsx
web/src/pages/home/monitor/strategy-group/index.tsx
web/src/pages/home/monitor/strategy-group/options.tsx
web/src/pages/home/monitor/strategy-group/strategy/index.tsx

feat: web table row delete feature

---

pkg/agent/datasource/p8s/prometheus.go

hotfix(datasource): 读写锁异常问题

---

web/src/pages/home/child/AddDashboardModal.tsx
web/src/pages/home/child/ConfigDashboardChart.tsx

issue: https://github.com/aide-family/moon/issues/125

feat(dashboard): 增加大盘删除功能 (#125)

---

app/prom_server/configs/config.yaml
app/prom_server/internal/biz/notify_template.go

hotfix(notify): 模版更新错误问题

---

web/src/pages/home/monitor/alarm-realtime/index.tsx

hotfix: fix issue about #141

---

app/prom_server/internal/data/repositiryimpl/msg/msg.go
web/src/pages/home/monitor/strategy-group/strategy/options.tsx

feat(sendInterval): 增加告警通知间隔配置 #147

---

pkg/util/interflow/hook/hook_http.go

hotfix(Send): 修复发送告警agent报错 #151

---

api/admin/history/alarm.proto
cmd/server/palace/internal/biz/bo/history.go
cmd/server/palace/internal/data/repoimpl/history.go
cmd/server/palace/internal/data/repoimpl/realtime_alarm.go
cmd/server/palace/internal/service/builder/history.go

fix:Batch update failure

---

cmd/server/houyi/internal/server/strategy_watch.go
cmd/server/palace/internal/data/repoimpl/alarm_raw.go

fix:alarm status cannot be updated.

---

README-zh.md
README.md

update: README demo URL

---

cmd/server/rabbit/internal/biz/config.go
cmd/server/rabbit/internal/biz/msg.go

fix:alarm sending email failure issue

---

cmd/server/palace/internal/data/repoimpl/realtime_alarm.go

The bug of querying the alarm page in real-time alerts is fixed
Fixes #
```release-note
```

fix:alert page bug

---

pkg/houyi/mq/mq.go
pkg/util/go/go.go
pkg/util/go/go_test.go

- 实现了一个协程池管理器，支持设置协程池大小和缓冲区大小
- 提供了全局的 Go 函数，方便在任何地方使用协程池
- 增加了协程池的启动和停止功能
- 添加了测试用例，验证协程池的基本功能
Fixes #
```release-note
```

feat(util): 添加协程池管理工具

---

cmd/server/palace/internal/biz/bo/metric.go
cmd/server/palace/internal/biz/metric.go
cmd/server/palace/internal/biz/repository/metric.go
cmd/server/palace/internal/data/repoimpl/metric.go
pkg/houyi/datasource/prometheus_test.go
pkg/palace/model/bizmodel/datasource_metrics.go
pkg/palace/model/bizmodel/metric_labels.go

fix:修复同步metric元数据入库逻辑

---

api/admin/alarm/time_engine_rule.proto

refactor: 将状态字段设为可选以适应不同场景

---

cmd/server/palace/internal/data/init.go

fix:修复业务库客户端资源关闭缺陷

---

cmd/server/palace/internal/biz/alarm.go
pkg/palace/model/alarmmodel/realtime_alarm.go

Fixed the real-time alarm storage bug

---

cmd/server/houyi/internal/biz/bo/strategy_event.go
pkg/label/label.go
pkg/util/format/format.go
pkg/util/format/format_test.go

feat: formatting event policy messages

---

Makefile

build(Makefile): Optimize the build

---

cmd/server/palace/internal/data/repoimpl/realtime_alarm.go

- 移除了不必要的指纹查询条件
- 仅使用 ID 进行查询，以解决查询错误问题
Fixes #
```release-note
```

Fix the error in real-time alarm query conditions

---

cmd/server/palace/internal/biz/bo/auth/oauth.go

Modify the verification rules for third-party login

---

cmd/houyi/internal/server/swagger/openapi.yaml
cmd/laurel/internal/server/swagger/openapi.yaml
cmd/palace/internal/server/swagger/openapi.yaml
cmd/rabbit/internal/server/swagger/openapi.yaml
i18n/en.toml
i18n/ja.toml
i18n/zh.toml
proto/api/common/server.proto
proto/api/palace/alert.proto
proto/api/palace/common/common.proto
proto/api/palace/common/common_enum.proto
proto/api/palace/invite.proto
proto/api/palace/message.proto

Add some API interfaces
